 12 lines (11 sloc) 687 Bytes
# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)                 
PRINT_ALL_FILES: false
FILTER_REGEX_EXCLUDE: "(\.github)"
SHOW_ELAPSED_TIME: true
GITHUB_STATUS_REPORTER: true